import SNN2.src.model.callbacks.reinforcement
import SNN2.src.model.callbacks.verbose
import SNN2.src.model.callbacks.saveEmbeddings
import SNN2.src.model.callbacks.testParam
import SNN2.src.model.callbacks.FastReplayMemory
import SNN2.src.model.callbacks.FakeReinforceFixedAction
import SNN2.src.model.callbacks.RL_env_manager
import SNN2.src.model.callbacks.RL_partial_manager
import SNN2.src.model.callbacks.ott_accuracy
import SNN2.src.model.callbacks.activate_metric
import SNN2.src.model.callbacks.ControlledMarginIncreas
import SNN2.src.model.callbacks.ControlledCrossEntropy
import SNN2.src.model.callbacks.ControlledCrossEntropy_better
