name: Generate Documentation

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('SNN/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev

    - name: Change to SNN directory and install requirements
      run: |
        cd SNN
        python -m pip install --upgrade pip
        grep -v '^\-e' requirements.txt | cut -d = -f 1 | xargs -n1 pip3 install -U

    - name: Install package in editable mode
      run: |
        cd SNN
        python -m pip install -e .

    - name: Generate documentation
      run: |
        cd SNN
        make docs

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: SNN/docs/public/

    - name: Deploy to GitHub Pages (on main branch only)
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: SNN/docs/public/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: documentation
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4